apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-app
  template:
    metadata:
      labels:
        app: cpu-app
    spec:
      containers:
      - name: cpu-app
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do :; done"
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
